# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200)),
                ('transcription', models.CharField(max_length=30)),
                ('russian', models.CharField(max_length=250)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_data', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dictionary.English_word')),
            ],
        ),
    ]
