# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='english_word',
            name='id',
        ),
        migrations.AlterField(
            model_name='english_word',
            name='english',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
