# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0003_auto_20170216_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English_word',
            new_name='EnglishWord',
        ),
    ]
