# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0004_auto_20170217_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Statistics',
        ),
    ]
