# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0005_auto_20170218_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='search_data',
            new_name='date',
        ),
    ]
