# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0006_auto_20170218_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(verbose_name='auto_now_add=True'),
        ),
    ]
