# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0007_auto_20170218_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
