# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0008_auto_20170227_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='english_word',
            new_name='english',
        ),
    ]
