# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0009_auto_20170227_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='data',
        ),
        migrations.RemoveField(
            model_name='englishword',
            name='id',
        ),
        migrations.AddField(
            model_name='englishword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 16, 25, 25, 658947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='english',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 16, 25, 25, 678960, tzinfo=utc)),
        ),
    ]
