# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0012_auto_20170319_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishword',
            name='access_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='englishword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 58, 0, 641300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 58, 0, 665532, tzinfo=utc)),
        ),
    ]
