# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0013_auto_20170320_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 10, 28, 0, 744944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 10, 28, 0, 809017, tzinfo=utc)),
        ),
    ]
