# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0014_auto_20170320_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='count',
        ),
        migrations.AddField(
            model_name='statistics',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 9, 12, 21, 321802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 9, 12, 21, 341068, tzinfo=utc)),
        ),
    ]
